### PR TITLE
gpgme: add gpgme_get_dirinfo

### PR DESCRIPTION
**Pull request by mochaaP**

### CODE REVIEW

**Comment by mochaaP** [comment]
Blocking: <https://github.com/maximbaz/yubikey-touch-detector/issues/52>

/cc @proglottis

**Comment by proglottis** [comment]
@mochaaP thanks for the MR. Sorry it's taken so long. Would it be possible to add a smoke test for this call?

Is there any reason this is targeting the 1.17 branch?

**Comment by mochaaP** [comment]
> Is there any reason this is targeting the 1.17 branch?

iirc the master branch stopped working for me after a certain Golang update, and I have only tested this on Golang 1.18+

**Comment by proglottis** [comment]
> iirc the master branch stopped working for me after a certain Golang update, and I have only tested this on Golang 1.18+

That's interesting. Perhaps I'll get that branch merged first :thinking:

**Comment by mochaaP** [comment]
Are we good to go?

**Comment by proglottis** [comment]
@mochaaP I think the implementation looks fine, but I would like a smoke test to be written too.

**Comment by mochaaP** [comment]
Will look at it later.

**Comment by mochaaP** [comment]
Not very sure where I should put the test: the field was read through `gpgconf` in C (instead of backends like assuan in `get_engine_info`). This function gets the 'system default' value, not the running ones.

**Comment by proglottis** [comment]
@mochaaP I think it would be sufficient to check only two cases:

- A totally unknown "what" to ensure the returned NULL gets handled properly
- Giving "homedir" (as per https://www.gnupg.org/documentation/manuals/gpgme/Engine-Version-Check.html) and checking that the returned string is not empty (since I'm assuming this value changes depending on the system).

**Comment by mochaaP** [comment]
added tests, changed interface to explicitly handle errors.

image

cc @proglottis

**Comment by mochaaP** [comment]
Are we ready for a merge?

**Comment by maximbaz** [comment]
A friendly ping @proglottis, would you have time to have a look at this PR? :slightly_smiling_face:

**Comment by proglottis** [comment]
Thank you @mochaaP I made some changes, but this MR has been merged. v0.1.4 released.

Sorry I didn't use the github UI :pray:

**Pull request closed without merging**
